from enum import Enum

# Pulled from https://api.crossref.org/types
class WorkType(Enum):
    BOOK = "book"
    BOOK_CHAPTER = "book-chapter"
    BOOK_SECTION = "book-section"
    BOOK_PART = "book-part"
    BOOK_SET = "book-set"
    BOOK_TRACK = "book-track"
    BOOK_SERIES = "book-series"
    JOURNAL = "journal"
    JOURNAL_ARTICLE = "journal-article"
    JOURNAL_VOLUME = "journal-volume"
    JOURNAL_ISSUE = "journal-issue"
    PROCEEDINGS = "proceedings"
    PROCEEDINGS_ARTICLE = "proceedings-article"
    PROCEEDINGS_SERIES = "proceedings-series"
    REPORT = "report"
    REPORT_SERIES = "report-series"
    REFERENCE_ENTRY = "reference-entry"
    REFERENCE_BOOK = "reference-book"
    STANDARD = "standard"
    STANDARD_SERIES = "standard-series"
    PEER_REVIEW = "peer-review"
    DISSERTATION = "dissertation"
    COMPONENT = "component"
    GRANT = "grant"
    DATASET = "dataset"
    EDITED_BOOK = "edited-book"
    MONOGRAPH = "monograph"
    POSTED_CONTENT = "posted-content"
    OTHER = "other"