@startuml
'https://plantuml.com/component-diagram
'Copyright 2022 Dennis Priskorn

[OpenAlexAPI]

cloud "OpenAlex" {
interface "HTTP JSON API" as httpoa
  'httpoa - [OpenAlex]
  [OpenAlexAPI] --> httpoa
}

@enduml